name: Preprod

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

env:
  KOIOS_JAVA_LIB_LOGGING: true

jobs:
  preprod:
    name: Preprod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Run tests
        run: |
          mvn '-Dtest=*Preprod*' verify -Djacoco.destFile=exportJacoco/jacoco-preview.exec -Dgpg.skip
      - name: Upload Jacoco Results
        uses: actions/upload-artifact@v2
        with:
          name: preview-tests-jacoco
          path: exportJacoco/jacoco-preview.exec